### ISSUE TITLE
Where can I find helper code for the book?

### ISSUE THREAD

**Issue by mqasimsarfraz** [bpftools/linux-observability-with-bpf#1]
While reading the book I am stuck at couple of examples and believe that I will need helper scripts mentioned in the book to continue. Is this the right place?

**Comment by fntlnz** [comment]
Hi @MQasimSarfraz thanks for reading our book and sorry for the inconvenience, those are supposed to go live for when the book is released, I believe you are reading the early preview.

I just pushed the examples I wrote #2 - @calavera is going to push the others soon!

**Comment by mqasimsarfraz** [comment]
Hi @fntlnz, Thanks for the response. I will go through the examples you added.

And yes I just realized that I am reading the early release. So I will close the issue! Great content btw! :+1:

**Comment by fntlnz** [comment]
Thank you @MQasimSarfraz !! Glad you like it

**Comment by Silvanoc** [comment]
> those are supposed to go live for when the book is released

Hasn't the book been released yet? I'm still missing some of the helper scripts...

**Comment by vmartino** [comment]
Same here

**Comment by sergeyfd** [comment]
Please. I have a paper copy from KubeCon and can't compile any code from it in any available for me OS.
